urls.py
from django.conf.urls.defaults import *
from django.views.generic import TemplateView
from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'back.views.home', name='home'),
    # url(r'^back/', include('back.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^messages/', include('messages.urls')),
    url(r'^', include('social_auth.urls')),
    url(r'^', include('registration.urls')),
    url(r'^', include('myproject.fishing.urls')),
    url(r'^', include('myproject.gprofile.urls')),
    url(r'^$', TemplateView.as_view(template_name="index.html")),
    url(r'^about/$', TemplateView.as_view(template_name="about.html")),
    url(r'^contact/$', TemplateView.as_view(template_name="contact.html")),
    url(r'^dashboard/$', TemplateView.as_view(template_name='dashboard/controlpanel.html')),
)

urlpatterns += patterns('myproject.views',
                        url('^thanks/$', 'contact_response'),
)

fishing/models.py
import sys
import math
import pycurl, urllib

from django.utils import simplejson as json
from django.conf import settings
from django.core.exceptions import ValidationError, ObjectDoesNotExist
from django.contrib.contenttypes.models import ContentType
from django.db import models, connection, transaction
from django.db.models.signals import post_save
from django.dispatch import receiver, Signal

from myproject.custom import GoogleLatLng, resize_image
from myproject.location.models import Country, State, BaseLocation, LocationManager
from myproject.customer.models import CustomerCore

# Create your models here.

WATER_TYPES = (('FW', 'Freshwater'),
               ('SW', 'Saltwater'))

WATERBODY_TYPES = (
    'Loch',
    'Canal',
    'Brook',
    'Ocean',
    'Creek',
    'Sea',
    'Lake',
    'River',
    'Stream',
    'Basin',
    'Bay',
    'Bayou',
    'Channel',
    'Strait',
)    

make_thumbnail = Signal(providing_args={'instance', 'max_size'})

class WaterBody(models.Model):
    name = models.CharField("Name of Water Body", max_length=150, unique=True)
    state = models.ForeignKey(State, blank=True, null=True)
    country = models.ForeignKey(Country, null=True, blank=True)
    locations = models.ManyToManyField(BaseLocation, through='GeoRelations', verbose_name="Nearby Locations", blank=True, editable=False, null=True, related_name="WaterBodies")
    lat = models.FloatField(blank=True, default=1000.0, editable=False)
    lng = models.FloatField(blank=True, default=1000.0, editable=False)
    json_response = models.CharField(max_length=2000, editable=False, blank=True, null=True)
    
    objects = models.Manager()
    neighbours = LocationManager()

    def __unicode__(self):
        return self.name
    
    def associate_locations(self, loc_model=BaseLocation, radius=100, use_miles=True):
        near = loc_model.neighbours.nearby_locations(self.lat, self.lng, radius, use_miles)
        for l in near:
            try:
                r = GeoRelations.objects.get(location__exact=l, water__exact=self)
            except:
                r = GeoRelations(location=l, water=self, verified=True)
                r.save()

    def clean(self, **kwargs):
        mquery = kwargs.get('mquery')
        if self.name or mquery:
            if not mquery:
                mquery = GoogleLatLng()
                state = self.state.name if self.state else ''
                country = self.country.abbr if self.country else ''
                if not mquery.requestLatLngJSON(self.name + ', ' + state + ', ' + country, True):
                    raise ValidationError("There is an error in the location string")
            l = mquery.parseLocation() # Again assume that all args to clean with mquery pass this test
            if not l:
                raise ValidationError("This body of water could not be found")
            self.json_response = mquery.results
            self.name = l[0]
            if len(l) > 1:
                newcountry, created = Country.objects.get_or_create(abbr=l[-1][1], name=l[-1][0],
                                                                    defaults={'abbr':l[-1][1], 'name':l[-1][0]})
                self.country = newcountry
            else:
                self.country = None
            if len(l) > 2:
                newstate, created = State.objects.get_or_create(key=l[-2][1], name=l[-2][0], country=self.country,
                                                                defaults={'key':l[-2][1],
                                                                          'name':l[-2][0],
                                                                          'country':self.country})
                self.state = newstate
            else:
                self.state = None
            self.lat = mquery.lat
            self.lng = mquery.lng

    def save(self, mquery=None, *args, **kwargs):
        self.clean(mquery=mquery)
        if mquery:
            try:
                test = WaterBody.objects.get(lat=self.lat, lng=self.lng)
            except ObjectDoesNotExist:
                pass
            else:
                return
        super(WaterBody, self).save(*args, **kwargs)

    class Meta:
        verbose_name = "Body of Water"
        verbose_name_plural = "Bodies of Water"
        unique_together = ('lat', 'lng')

class GeoRelationsManager(models.Manager):
    def user_edit(self, loc, wat, cust):
        """
        loc is a BaseLocation object,
        wat is a WaterBody object,
        cust is a CustomerCore object
        """
        newrel = self.model(location=loc, water=wat, added_by=cust)
        newrel.save()
        return newrel

class GeoRelations(models.Model):
    location = models.ForeignKey(BaseLocation)
    water = models.ForeignKey(WaterBody)
    verified = models.BooleanField(blank=True, default=False)
    added_by = models.ForeignKey(CustomerCore, null=True, related_name="GeoRelations")
    added_on = models.DateTimeField(auto_now_add=True)

    custom = GeoRelationsManager()
    objects = models.Manager()

    def __unicode__(self):
        return '%s - %s' % (self.location, self.water)

    def verify(self):
        self.verified = True

    class Meta:
        verbose_name = "Geographic Relationship"
        unique_together = ('location', 'water')

class Fish(models.Model):
    name = models.CharField("Name of Fish", max_length=30)
    type = models.CharField("Type of Fish", max_length=30)
    water_type = models.CharField("Water Habitat of Fish", max_length=2, choices=WATER_TYPES)
    alternate_name_1 = models.CharField(max_length=30, blank=True, null=True)
    alternate_name_2 = models.CharField(max_length=30, blank=True, null=True)
    alternate_name_3 = models.CharField(max_length=30, blank=True, null=True)
    image = models.ImageField(upload_to='fishimages/', blank=True, null=True)
    verified = models.BooleanField(default=False, blank=True)

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Fish"
        unique_together = ("name", "type", "water_type")

    def save(self, *args, **kwargs):
        try:
            this = Fish.objects.get(id=self.id)
            if this.image != self.image:
                this.image.delete()
        except:
            pass
        super(Fish, self).save(*args, **kwargs)

class FishingType(models.Model):
    method = models.CharField("Type of Fishing Trip", max_length=100, unique=True)
    image = models.ImageField(upload_to='typeimages/', blank=True, null=True)
    verified = models.BooleanField(default=False, blank=True)

    def __unicode__(self):
        return self.method

    class Meta:
        verbose_name = "Fishing Type"

    def save(self, *args, **kwargs):
        try:
            this = FishingType.objects.get(id=self.id)
            if this.image != self.image:
                this.image.delete()
        except:
            pass
        super(FishingType, self).save(*args, **kwargs)

class InheritanceCastModel(models.Model):
    """
    An abstract base class that provides a ``real_type`` FK to ContentType.
    
    For use in trees of inherited models, to be able to downcast
    parent instances to their child types.
    """
    real_type = models.ForeignKey(ContentType, editable=False, null=True)
    
    def save(self, *args, **kwargs):
        if not self.id:
            self.real_type = self._get_real_type()
        super(InheritanceCastModel, self).save(*args, **kwargs)

    def _get_real_type(self):
        return ContentType.objects.get_for_model(type(self))

    def cast(self):
        return self.real_type.get_object_for_this_type(pk=self.pk)

    class Meta:
        abstract = True

class BaseBrand(InheritanceCastModel):
    guide = models.ManyToManyField('gprofile.GuideCore', related_name='%(app_label)s_%(class)s_related')
    brand = models.CharField(max_length=200, unique=True)
    image = models.ImageField(upload_to='logos/', blank=True, null=True)
    verified = models.BooleanField(default=False)

    def __unicode__(self):
        return self.brand

    class Meta:
        abstract = True

    def save(self, *args, **kwargs):
        try:
            this = self.cast()
            if this.image != self.image:
                this.image.delete()
        except:
            pass
        super(BaseBrand, self).save(*args, **kwargs)
        make_thumbnail.send(sender=BaseBrand.__name__, instance=self, max_size=(100,100))

class LureBrand(BaseBrand):
    class Meta:
        verbose_name = "Lure Brand"

class RodBrand(BaseBrand):
    class Meta:
        verbose_name = "Rod Brand"

class ReelBrand(BaseBrand):
    class Meta:
        verbose_name = "Reel Brand"

class LineBrand(BaseBrand):
    class Meta:
        verbose_name = "Line Brand"

class BaitBrand(BaseBrand):
    class Meta:
        verbose_name = "Bait Brand"

class GuideEngine(models.Model):
    guide = models.ForeignKey('gprofile.GuideCore')
    engine_brand = models.ForeignKey('EngineBrand')
    horsepower = models.IntegerField(help_text="Enter the hp of this engine")
    model = models.CharField(max_length=100, blank=True, null=True)

    class Meta:
        verbose_name = "Engine Brands for Guide"
        verbose_name_plural = "Engine Brands for Guide"

    def __unicode__(self):
        return engine_brand.__unicode__() + ' for ' + guide.__unicode__()

class EngineBrand(models.Model):
    brand = models.CharField(max_length=200)
    image = models.ImageField(upload_to='logos/', blank=True, null=True)
    verified = models.BooleanField(default=False)
    guide = models.ManyToManyField('gprofile.GuideCore', blank=True, null=True, through=GuideEngine, related_name='EngineBrands')
    
    class Meta:
        verbose_name = "Engine Brand"

    def __unicode__(self):
        return self.brand

    def save(self, *args, **kwargs):
        try:
            this = EngineBrand.objects.get(id=self.id)
            if this.image != self.image:

templates/display.html
{% extends "base.html" %}

{% block head0 %}
		<!-- CSS -->
		<link href="{{ CSS_URL }}display.css" rel="stylesheet" type="text/css" />
        <link type="text/css" href="{{ MEDIA_URL }}jQueryUI/themes/start/jquery-ui-1.8.13.custom.css" rel="stylesheet"/>
		<link rel="stylesheet" type="text/css" href="{{ CSS_URL }}jquery.autocomplete.css" />
		<!-- jQuery and Javascript -->		
		<script type="text/javascript" src="{{ MEDIA_URL }}jQueryUI/jquery-1.5.1.js"></script>	
		<script type="text/javascript" src="http://code.jquery.com/jquery-1.6.1.min.js"></script>
		<script type="text/javascript" src="{{ MEDIA_URL }}jQueryUI/ui/jquery-ui-1.8.13.custom.js"></script>
		<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
		<script type="text/javascript" src="{{ JS_URL }}jquery.ajaxQueue.js"></script>
		<script type="text/javascript" src="{{ JS_URL }}jquery.bgiframe.min.js"></script>
		<script type="text/javascript" src="{{ JS_URL }}jquery.js"></script>
		<script type="text/javascript" src="{{ JS_URL }}jquery.autocomplete.js"></script>
		<script>
    			jq = jQuery.noConflict(true);
		</script>
		<script type="text/javascript" src="{{ JS_URL }}display.js"></script>
		
		<title>Search Results Page</title>
{% endblock %}


{% block body0 %}
	<div class="container-fluid">
        <div class="row-fluid">

        	<div id="left-panel" class="span3">
				<a href="{{ DOMAIN }}">
					<img id="logo-small" src="{{ MEDIA_URL }}logo.png"/>
				</a>    
                <div id="map_canvas"></div> 
                <div id="adv_search">
                	<h2> Advanced Search </h2>
		                <!-- Fish Type -->
                        <div class="ui-widget">
                            <label>Fish Species:</label>
                            <select id="fish_species">
                                <option value="">No Preference</option>
                                <option value="walleye">Walleye</option>
                                <option value="bass">Bass</option>
                                <option value="perch">Perch</option>
                                <option value="bluegill">Bluegill</option>
                                <option value="shark">Shark</option>
                                <option value="tuna">Tuna</option>
                                <option value="pike">Pike</option>
                                <option value="barracuda">Barracuda</option>		
                            </select>
                        </div>
                        <div class="ui-widget">
                            <label>Fishing Type</label>
                            <select id="fishing_type">
                                <option value="">No Preference</option>	
                                <option value="fly">Fly Fishing</option>
                                <option value="troll">Trolling</option>
                                <option value="kayak">Kayak Fishing</option>
                                <option value="lure">Lure Fishing</option>
                                <option value="ice">Ice Fishing</option>
                            </select>
                        </div>
	                   	<!--Price-->
                    	<p id="price_range">
               	    		<label for="price_amount">Price range:</label>
                	    </p>
                    	<p id="price_amount"></p>
                    	<div id="slider-range"></div>
            
    	                <!--Salt or Fresh-->
                    	<form>
                        	<p id="water_type">Water Type</p>
                        	<div id="radio">
                        	    <input type="radio" id="radio1" name="radio" /><label for="radio1">Salt</label>
                        	    <input type="radio" id="radio2" name="radio"  /><label for="radio2">Fresh</label>
                        	    <input type="radio" id="radio3" name="radio" checked="checked"/><label for="radio3">Either</label>
                        	</div>
                    	</form>
		
		                <div class="advanced">
        		        	<div id="dialog" title="Advanced Search Options">
                	    		<form id="advanced_search" action="javascript:closePopup();" method="get">
                            		<ul id="advanced_list">
                                		<li>
                                    		<input type="checkbox" id="kid_friendly" name="kid_friendly" value="kid_friendly">
                                    		<label for="kid_friendly">Kid Friendly</label>
                                		</li>
                                		<li>
                                    		<input type="checkbox" id="equipment_provided" name="equipment_provided" value="equipment_provided">
                                    		<label for="equipment_provided">Equipment Provided</label>
                                		</li>
                                		<li>
                                    		<input type="checkbox" id="alcohol_allowed" name="alcohol_allowed" value="alcohol_allowed">
                                    		<label for="alcohol_allowed">Alcohol Allowed</label>
                                		</li>
                                		<li>
                                    		<input type="checkbox" id="state_certified" name="state_certified" value="state_certified">
                                    		<label for="state_certified">State Certified</label>
                                		</li>
                                		<li>
                                    		<input type="checkbox" id="fillet_service" name="fillet_service" value="fillet_service">
                                    		<label for="fillet_service">Fillet Services Included</label>
                                		</li>
                                		<li>
                                    		<input type="checkbox" id="food" name="food" value="food">
                                    		<label for="food">Food Provided</label>
                                		</li>
		                                <li>
		                                    <input type="checkbox" id="coast_guard" name="coast_guard" value="coast_guard">
		                                    <label for="coast_guard">Coast Guard Certified</label>
		                                </li>
		                                <li>
		                                    <input type="checkbox" id="taxidermy" name="taxidermy" value="taxidermy">
		                                    <label for="taxidermy">Taxidermy Services Available</label>
		                                </li>
		                                <li>
		                                    <input type="checkbox" id="handicapped" name="handicapped" value="handicapped">
		                                    <label for="handicapped">Handicapped Accessible</label>
		                                </li>
		                            </ul>
		                    		<div>
    		                    		<a href="javascript:void(0);" onclick="closePopup();">Cancel</a> 
        		                		<input id="advanced_submit" type="submit" value="Search">
                					</div>
                	        	</form>
                    		</div>
                		</div>
                	</div>
                	<button id="opener">Advanced Search Options</button>
			</div> <!--end left panel -->

			<div id="right-panel" class="span8">
                <div id="display_header" class="span8">
                   <form id="search_form" action="{{ DOMAIN }}display/" method="get">
                            <!-- Location -->
                            <input id = "display_loc" class="span5" type= "text" name="loc"
                            value = "{{ request.GET.loc }}" onfocus="clickclear(this, ' city, state, country')"
                            onblur="clickrecall(this, ' city, state, country')"/>
                        
                            <!-- Calendar  -->
                            <input type="text" name="date" id="date" class="span2"  
                            value = "{{ request.GET.date }}"
                            onfocus="clickclear(this, ' Date')"
                            onblur="clickrecall(this, ' Date')" />
                    
                            <!-- Added by Sid: Hidden inputs -->
                            <input type="hidden" name="lat" id="id_lat" />
                            <input type="hidden" name="lng" id="id_lng" />
                    
                            <!-- Submit -->
                            <input type="submit" id="button" value="Search" class="btn-large"/>
                    </form>
                </div><!--end of display header-->
                
                <!--Sort Bar-->
                <div id="sort-bar">
                    <h3 class="span2"> Sort guides by:</h3>
                    <form>
                        <div id="sort-drop">
                            <select id="sort-by">
                                <option>Recommended</option>
                                <option>Price</option>
                                <option>Distance</option>
                            </select>
                        </div>
                    </form>
                </div><!--end sort bar-->

                <div id="results_filters">
                    <div id="filters_text">
                        Filters: 
                    </div>
                    <ul id = "applied_filters">
                        <li id = "applied_filter_fish_species" class = "hide">
                            <span class="af_text">Fish Species</span>
                        <a class="filter_x_container">
                            <div class="filter_x"></div>
                        </a>
                        </li>
                        <li id = "applied_filter_price" class = "left hide">
                            <span class="af_text">Price</span>
                        <a class="filter_x_container">
                            <div class="filter_x"></div>
                        </a>
                        </li>
                    </ul>
                </div>
                    
                <!-- loop over all guides -->
                <div class="all_guides span8" id="stuff">
	                {% if guides_list %}
	             
		                {% for guide in guides_list %}
		                	<div class="guide_wrap">
								<a href="{{ guide.person.get_pretty_url }}"><img class="guide_pic" src="{{ guide.profile.cust_profile.profile_pic.thumb.url }}"/></a>
		                        
                                <div class="guide_loc"><p>{{ guide.person.contact.city }}, {{ guide.person.contact.state.key }}, {{ guide.person.contact.country.abbr }}</p></div>
                            
                                {% if guide.company %}
		                        	<a href="{{ guide.person.get_pretty_url }}"><div class="guide_biz"><strong>{{ guide.company }}</strong></div></a>
		                            <div class="guide_name_biz">(Guide: {{ guide.person.full_name }})</div>
		                        {% else %}
		                       	    <a href="{{ guide.person.get_pretty_url }}"><div class="guide_name"><strong>{{ guide.person.full_name }}</strong></div></a>
		                        {% endif %}
		                     
			                	<div class="guide_info">
		                            <p class="info_p"><b>Specialties:</b> {% for fish in guide.fish.all %}{{ fish.name }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>

		                            <p class="info_p"><b>Pricing: </b>Full Day = &#36;{{ guide.full_day_price }}</p>

		                            <p class="info_p"><b>Years of Experience: </b>{{ guide.experience }}</p>
				                            <script type = "text/javascript"> 
				                                var csc = "{{ guide.person.contact.city }}, {{ guide.person.contact.state.key }}, {{ guide.person.contact.country.abbr }}";
				                                newLocations.push(csc);
				                            </script>
			                 	</div><!-- end guide_info -->   
			                 </div><!-- end guide_wrap -->

		                {% endfor %}
	            
	                {% else %}<!-- if search has no matches -->
	                
	                	<div id="empty_wrap">
	                    <h2>Sorry, your search didn't hook any guides...</h2>
	                    <img src="{{ MEDIA_URL }}blob.jpg" alt="sad fish" width="304"/>
	                    <p>Perhaps try broadening your search by only specifying an area, or picking your own hometown to see a picture of yourself (coming soon...)</p>
	                	</div>
	                     
	                {% endif %}
            	</div><!-- end all_guides -->
                
            	<script type = "text/javascript">
                	initialize("{{ request.GET.loc }}");
            	</script>
            </div><!--end right-panel -->

    	</div> <!--end row-fluid -->     
    </div> <!-- end container-fluid -->

{% endblock %}<!--end body0-->

templates/down.html
{% extends "base.html" %}

{% block head0 %}
<title>The Guide Findeer is undergoing an upgrade</title>
{% endblock %}

{% block body0 %}
<h1>The Website is undergoing an Upgrade!</h1>
<br/>
<p>We are going to be back with a better, faster and more beautiful site. Stay tuned.</p>
{% endblock %}

templates/index.html
{% extends "base.html" %}

{% block head0 %}
{% block head1 %}

<link href="{{ CSS_URL }}index.css" rel="stylesheet" type="text/css" />

<title>TheGuideFinder: Home</title>

<!-- jQuery -->
<script type="text/javascript" src="http://code.jquery.com/jquery-1.6.1.min.js"></script> 

<!-- jQuery Autocomplete -->
<script type="text/javascript" src="{{ JS_URL }}jquery.ajaxQueue.js"></script>
<script type="text/javascript" src="{{ JS_URL }}jquery.bgiframe.min.js"></script>
<script type="text/javascript" src="{{ JS_URL }}jquery.js"></script>
<script type="text/javascript" src="{{ JS_URL }}thickbox-compressed.js"></script>
<script type="text/javascript" src="{{ JS_URL }}jquery.autocomplete.js"></script>
<link rel="stylesheet" type="text/css" href="{{ CSS_URL }}jquery.autocomplete.css" />
<script>
    jq = jQuery.noConflict(true);
</script>
<link rel="stylesheet" type="text/css" href="{{ CSS_URL }}thickbox.css" />

<!-- jQuery UI -->
<link type="text/css" href="{{ CSS_URL }}jquery-ui-1.8.14.custom.css" rel="stylesheet"/>
<script type="text/javascript" src="{{ JS_URL }}jquery-ui-1.8.14.custom.min.js"></script>
<script type="text/javascript" src="{{ JS_URL }}jquery.ui.autocomplete.js"></script>
<script type="text/javascript" src="{{ JS_URL }}jquery.ui.core.js"></script>
<script type="text/javascript" src="{{ JS_URL }}jquery.ui.position.js"></script>
<script type="text/javascript" src="{{ JS_URL }}jquery.ui.widget.js"></script>

{% endblock %}
{% endblock %}

{% block script0 %}

<script type="text/javascript">
function clickclear(thisfield, defaulttext) {
if (thisfield.value == defaulttext) {
    thisfield.value = ""; }
}

function clickrecall(thisfield, defaulttext) {
if (thisfield.value == "") {
    thisfield.value = defaulttext; }
}
</script>

<script type = "text/javascript">
$(function() {
         var locationTags = [
	     "Charleston, SC, USA",
	     "Boston, MA, USA",
	     "New York City, NY, USA",
	     "Los Angeles, CA, USA",
	     "Detroit, MI, USA",
            "San Diego, CA, USA",
	     "Florida",
	     "South Dakota",
	     "South Carolina",
	     "Montana",
	     "Connecticut",
	     "New York",
	     "Washington",
	     "Missouri",
	     "Dover, DE, USA",
	     "Brooklyn, NY, USA",
	     "Miami, FL, USA",
	     "Minneapolis, MN, USA",
	     "San Francisco, CA, USA",
	     "La Jolla, CA, USA",
	     "Kansas City, MO, USA",
	     "New Orleans, LA, USA",
	     "Aberdeen, SD, USA",
	     "Rapid City, SD, USA",
	     "Pierre, SD, USA",
	     "Red Lodge, MT, USA",
	     "Pittsburgh, PA, USA",
            "Washington DC, DC, USA",
	     "Chicago, IL, USA",
	     "Vancouver, CT, USA",
            "Hamden, CT, USA",
            "Portland, WA, USA",
	     "USA",
	     "California"
	     ];
	 jq("#loc").autocomplete( locationTags, {
		    minChars: 1,
		    autoFill: true,
		    matchContains: false,
		    scrollHeight: 220
		   });
});


<!-- Date -->
$(function() {
$( "#date" ).datepicker();
});

//(function( $ ) {

//$( ".ui-autocomplete-input" ).live( "autocompleteopen", function() {
//    var autocomplete = $( this ).data( "autocomplete" ),
//        menu = autocomplete.menu;

//    if ( !autocomplete.options.selectFirst ) {
//        return;
//    }

//    menu.activate( $.Event({ type: "mouseenter" }), menu.element.children().first() );
//});

//}( jQuery ));

</script>

<script type="text/javascript">
$(window).load(function() {
    $('#slider').nivoSlider();
});
</script>


{% endblock %}




{% block body0 %}

		<a href="{{ DOMAIN }}"><img id="logo-splash" src="{{ MEDIA_URL }}logo.png"/></a>

		<div id="myCarousel" class="carousel slide">
		    <!-- Carousel items -->
		    <div class="carousel-inner">
		      <div class="active item">
		        <img alt="" src="{{ MEDIA_URL }}slider/slider1.jpg" />
		        <div class="carousel-caption"><p>Caption 1</p></div>
		      </div>
		      <div class="item">
		         <img alt="" src="{{ MEDIA_URL }}slider/slider3.jpg" />
		          <div class="carousel-caption"><p>Caption 2</p></div>
		      </div>
		      <div class="item">
		         <img alt="" src="{{ MEDIA_URL }}slider/slider4.jpg" />
		          <div class="carousel-caption"><p>Caption 3</p></div>
		      </div>
		    </div>
		    
		    <!-- Carousel nav -->
		    <a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
		    <a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
	  	</div>
        
		<div id="wrap">
		<form id="search_form" action="{{ DOMAIN }}display/" method="get">

		<!-- Location -->
		<div class = "ui-widget">
		<input id = "loc" type= "text" name="loc"
		 value = " Where do you want to fish?"
		 onfocus="clickclear(this, ' Where do you want to fish?')"
		 onblur="clickrecall(this, ' Where do you want to fish?')" />
		</div>
				
		 <!-- Calendar  -->
		<input id="date" type="text" name="date"
		 value = " Date"
		 onfocus="clickclear(this, ' Date')"
		 onblur="clickrecall(this, ' Date')"/>

		 <!-- Added by Sid: Hidden lat and lng inputs -->
		 <input id="id_lat" type="hidden" name="lat"/>
		 <input id="id_lng" type="hidden" name="lng"/>
		
		<!-- Submit -->
		<input type="submit" id="button" value="Find a Guide" />

		 </form>
		 </div>

	<hr id="line"/>
	
	<h2 id="easy_header">It's as easy as...</h2>

	<div id="tri_box_wrap">
	    <div class="tri_box">
	        <h3>1. Find fishing guides nearby</h3>
	        <img class="tri_pic" id="map" src="{{ MEDIA_URL }}images/index/m_map.png"/>
	        <p id = "map_text">
	       		Search our growing community of certified fishing guides by entering your location into the search bar above.  Find the top guides in your state, city, or nearby body of water.
	        </p>
	    </div>
	    <div class="tri_box">
	    	<h3>2. Pick the right one for you</h3>
	        <img class="tri_pic" id="fish" src="{{ MEDIA_URL }}images/index/m_fish.png"/>
	    	<p id = "fish_text">
				There are many types of guides, just as there are many types of fishermen.  Compare and sort guides by price, fish species, client reviews, and many other important factors.
			</p>
		</div>
	    <div class="tri_box">
	        <h3>3. Book the trip, Hit the water!</h3>
   	        <img class="tri_pic" id="calendar" src="{{ MEDIA_URL }}images/index/m_cal.png"/>
	    	<p id = "cal_text">
				Get simple, secure, and instant booking for your next fishing adventure.  Leave your wallet at home and pay online - just like a plane ticket or hotel room.
			</p>
	    </div>
	</div> <!-- end tri_box_wrap -->


{% endblock %}
	     
	 

templates/thanks.html
{% extends "base.html" %}

{% block head0 %}
		<title>TheGuideFinder: Thank you&#33;</title>
{% endblock %}

{% block body0 %}
	<div class="header">
		<img src="{{ MEDIA_URL }}email icon.jpg">
	<!-- end of header --></div>
	<div class="content">
	<h1 id="heading"> Your message has been sent</h1>
	<p> As we continue to shape our services, input from alpha testers like you will be a guiding force in the final product.  Thanks for your time!</p>
	<!-- end of content --></div>
{% endblock %}